"""Rebuild the single shared stylesheet; no production dependency is needed."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
sources = ['theme.css', 'content.css', 'layout.css', 'performance.css']
css = '\n'.join((ROOT / 'assets' / name).read_text() for name in sources)
css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
css = re.sub(r'\s+', ' ', css).strip()
(ROOT / 'assets/site.css').write_text('/* Generated by build-shared-css.py. */\n' + css + '\n')
print(f'Built assets/site.css from {len(sources)} sources ({len(css)} bytes).')
